#!/usr/bin/env python3
"""Render the firmware's fixed Chinese lines to 1-bit bitmaps and emit a C header.

TFT_eSPI's built-in fonts are ASCII-only, so Chinese must be embedded. We
pre-rasterize each fixed line with a macOS CJK font and pack it in the
Adafruit-GFX bitmap layout (row-padded to a byte, MSB first) that
TFT_eSPI::drawBitmap() consumes. Dynamic ASCII (the SSID, the IP) is drawn at
runtime with the built-in font, so it is NOT generated here.

Run:  uvx --with pillow python3 tools/gen_zh_assets.py
Out:  zh_assets.h
"""
from PIL import Image, ImageDraw, ImageFont
import os

FONT = "/System/Library/Fonts/STHeiti Medium.ttc"
SIZE = 24
OUT = os.path.join(os.path.dirname(__file__), "..", "zh_assets.h")

# name -> text. Names become ZH_<NAME>_{W,H} and zh_<name> arrays.
LINES = {
    "sub":   "配网设置",
    "step1": "1. 连接下方热点",
    "step2": "2. 打开弹出页面",
    "step3": "3. 输入网络密码",
    "wait":  "已连接 · 等待状态",
}

font = ImageFont.truetype(FONT, SIZE)


def render(text):
    probe = ImageDraw.Draw(Image.new("L", (4, 4)))
    x0, y0, x1, y1 = probe.textbbox((0, 0), text, font=font)
    w, h = x1 - x0, y1 - y0
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), text, fill=255, font=font)
    px = img.load()
    byte_w = (w + 7) // 8
    data = []
    for y in range(h):
        for bx in range(byte_w):
            b = 0
            for bit in range(8):
                x = bx * 8 + bit
                b = (b << 1) | (1 if (x < w and px[x, y] >= 128) else 0)
            data.append(b)
    return w, h, data


def main():
    out = ["// AUTO-GENERATED by tools/gen_zh_assets.py — do not edit by hand.",
           "// 1-bit bitmaps for TFT_eSPI::drawBitmap (row-padded, MSB first).",
           "#pragma once", "#include <stdint.h>", ""]
    for name, text in LINES.items():
        w, h, data = render(text)
        rows = ", ".join(str(v) for v in data)
        out.append(f"// {text}")
        out.append(f"#define ZH_{name.upper()}_W {w}")
        out.append(f"#define ZH_{name.upper()}_H {h}")
        out.append(f"static const uint8_t zh_{name}[] = {{ {rows} }};")
        out.append("")
    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.abspath(OUT)}")
    for name, text in LINES.items():
        w, h, _ = render(text)
        print(f"  {name:6s} '{text}'  {w}x{h}px")


if __name__ == "__main__":
    main()
