#!/usr/bin/env python3
"""Convert the mascot PNGs (art/*.png) into an embeddable RGB565 header.

Each expression becomes a transparent-keyed sprite the firmware blits over a
soft state-coloured background. Transparent pixels are written as a magenta key
(0xF81F) that TFT_eSPI's pushImage skips.

Run:  uvx --with pillow python3 tools/gen_mascot_assets.py   ->  mascot_assets.h
"""
from PIL import Image
import os

ART = os.path.join(os.path.dirname(__file__), "..", "art")
OUT = os.path.join(os.path.dirname(__file__), "..", "mascot_assets.h")
SIZE = 240            # full screen (art has its own padding, so the blob isn't edge-to-edge)
KEY = 0xF81F          # magenta = transparent

# expression -> (png, soft background RGB).  Order/index must match the firmware
# enum: EX_NONE=0, EX_IDLE=1, EX_WORKING=2, EX_CONFIRM=3, EX_ERROR=4, EX_OFFLINE=5
# Backgrounds are pale pastels (blended toward white) so the cream mochi pops;
# offline stays a muted night colour (it's "asleep").
STATES = [
    ("idle",    "idle.png",    (205, 240, 212)),
    ("working", "working.png", (255, 238, 205)),
    ("confirm", "confirm.png", (208, 226, 255)),
    ("error",   "error.png",   (255, 214, 214)),
    ("offline", "offline.png", (48, 50, 70)),
]


def to565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def sprite(png):
    img = Image.open(os.path.join(ART, png)).convert("RGBA").resize((SIZE, SIZE), Image.LANCZOS)
    px = img.load()
    out = []
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b, a = px[x, y]
            out.append(KEY if a < 128 else to565(r, g, b))
    return out


def main():
    lines = ["// AUTO-GENERATED by tools/gen_mascot_assets.py — do not edit.",
             "#pragma once", "#include <stdint.h>", "",
             f"#define MASCOT_W {SIZE}", f"#define MASCOT_H {SIZE}",
             f"#define MASCOT_KEY 0x{KEY:04X}", ""]
    names = []
    for name, png, _ in STATES:
        data = sprite(png)
        names.append(name)
        body = ", ".join(f"0x{v:04X}" for v in data)
        lines.append(f"static const uint16_t mascot_{name}[{SIZE*SIZE}] = {{ {body} }};")
        lines.append("")
    # index tables (slot 0 = EX_NONE = none)
    imgs = "nullptr, " + ", ".join(f"mascot_{n}" for n in names)
    bgs = "0, " + ", ".join(f"0x{to565(*bg):04X}" for _, _, bg in STATES)
    lines.append(f"static const uint16_t* const MASCOT_IMG[] = {{ {imgs} }};")
    lines.append(f"static const uint16_t MASCOT_BG[] = {{ {bgs} }};")
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    sz = os.path.getsize(OUT)
    print(f"wrote {os.path.abspath(OUT)} ({sz//1024} KB, {SIZE}x{SIZE} x {len(STATES)} sprites)")


if __name__ == "__main__":
    main()
